### ISSUE TITLE
[質問/ヘルプ]設定画面の誕生日選択の実装方法が分からない

### ISSUE THREAD

**Issue by tttkouyou** [ISC-MakeIT/rackle_client#18]
## 実現したいこと

誕生日の日付を年、月、日で選ぶ。
ドラムロール式や、プルダウン式が望ましい。

## 問題点

膨大な日付をlistに入れてプルダウンにし、選択させるというのはあまり現実的な実装ではない。
何かいい方法がないかと調べた結果、DataPickerというやり方で選択できそうなのですが、これはカレンダーのようなUIが表示され、そこから日付を選ぶという形なので、目標とは違う。
他も調べたが、時間と日にちを一緒に取得したり、時間だけを取得したり、目標のドラムロール式やプルダウン式で日付を選択するというものは見つけることができなかった。

## 試した事とその結果

datapickerの参考URL
[https://flutter.ctrnost.com/basic/interactive/form/datapicker/](https://flutter.ctrnost.com/basic/interactive/form/datapicker/)

datetime picker(日付と時間)の参考URL
[https://www.virment.com/using-datetimepicker-in-flutter/](https://www.virment.com/using-datetimepicker-in-flutter/)

**Comment by isshun226** [comment]
これどうぞ
https://www.virment.com/using-datetimepicker-in-flutter/
https://github.com/virment/flutter-sample/blob/master/datetimepicker-sample/main.dart
