### ISSUE TITLE
技術調査&選定

### ISSUE THREAD

**Issue by isshun226** [ISC-MakeIT/rackle_client#4]
#3 にも書いているが、長くなるので分離。
- [x] UIライブラリ
- [x] GoogleMap
- [ ] routingのライブラリ
なんかあればまた追加していく

**Comment by isshun226** [comment]
# UIライブラリ
モダンなデザインでうざい要素がないので``Material.dart``使うと思う
暫定。

**Comment by isshun226** [comment]
# GoogleMap
``flutter_google_maps``で確定
調査はまだ完了していない為、チェックはまだつけません。
完了したらコメントつけてチェックつけてね @DuGlaser

**Comment by DuGlaser** [comment]
ドキュメント作成次第チェックつけます👌

**Comment by isshun226** [comment]
必要そうなのは問題ないのでclose
